system.iyzico:
  type: iyzipay_keys
  mapping:
    api_key:
      type: string
      label: 'API key'
    secret_key:
      type: string
      label: 'Secret key'
    api_url:
      type: string
      label: 'API URL'
